#!/bin/bash

. venv/bin/activate

OUT=out/$(echo "$*" | md5sum | cut -d ' ' -f1)

mkdir -p $OUT music
cd $OUT

echo "Output folder: $OUT"

pip install -U yt-dlp
yt-dlp --cookies-from-browser chrome:/home/user/snap/chromium/common/chromium/Default/ --cookies ../../cookies.txt 2>/dev/null

spotdl --format mp3 --output '{album-artist}/{album}/{title}.{output-ext}' --yt-dlp-args '-f mp3,m4a,webm --cookies ../../cookies.txt' --max-retries 5 --threads 6 --preload --save-errors ../../errors.log --id3-separator ', ' --log-level=DEBUG download $* --audio youtube-music youtube soundcloud --generate-lrc --lyrics genius synced --genius-access-token 'V1cJYvWbhzkZ8saefsEwi_ZVI1ZmPUjnNRb3XTvtgTN9YLEYNm5IuFrPqYbebjQQ'
